name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # Compile, build and test locally with mocked hardhat tasks
  build-and-test-local:
    runs-on: ubuntu-latest

    env:
      SEPOLIA_MNEMONIC: ${{ secrets.SEPOLIA_MNEMONIC }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable
      - run: npm ci
      - run: npm run prettier:check
      # - run: npm run lint
      - run: npm run compile
      - run: npm run build:ts
      - run: npm test
      - run: npm run coverage
  #
  deploy-and-test-sepolia:
    name: Deploy & Test on Sepolia
    runs-on: ubuntu-latest
    needs: build-and-test-local
    if: success()

    env:
      SEPOLIA_MNEMONIC: ${{ secrets.SEPOLIA_MNEMONIC }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable

      - run: npm ci
      - run: npm run compile

      - name: Deploy contracts to Sepolia
        run: npx hardhat deploy --network sepolia

      - name: Run Sepolia tests
        run: npx hardhat test --network sepolia
